export const SCHEDULER_NAME = 'SCHEDULER_NAME'
export const SCHEDULER_TYPE = 'SCHEDULER_TYPE'

export const SCHEDULE_CRON_OPTIONS = 'SCHEDULE_CRON_OPTIONS'
export const SCHEDULE_INTERVAL_OPTIONS = 'SCHEDULE_INTERVAL_OPTIONS'
export const SCHEDULE_TIMEOUT_OPTIONS = 'SCHEDULE_TIMEOUT_OPTIONS'
export const SCHEDULE_MODULE_OPTIONS = 'SCHEDULE_MODULE_OPTIONS'

export const SCHEDULER_LOGGER_INJECTOR = Symbol('Logger injector')
export const SCHEDULER_METRICS_INJECTOR = Symbol('Metrics injector')
